# Generated by Django 5.1.4 on 2025-05-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_podcast', models.IntegerField()),
                ('media_link', models.CharField(max_length=255)),
                ('date_add', models.DateField()),
                ('durations', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item', models.IntegerField()),
                ('type_item', models.IntegerField()),
                ('id_genre', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='podcast',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
