# Generated by Django 5.1.4 on 2025-06-12 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_author_genre_group_authors_group_episodes_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode_genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast_genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Item_genre',
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='episode',
            name='id_podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.podcast'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='media_link',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='group_authors',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group_authors',
            name='id_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author'),
        ),
        migrations.AlterField(
            model_name='group_authors',
            name='id_podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.podcast'),
        ),
        migrations.AlterField(
            model_name='group_episodes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group_episodes',
            name='id_episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.episode'),
        ),
        migrations.AlterField(
            model_name='group_episodes',
            name='id_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_groups'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='id_episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.episode'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user_groups',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_groups',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AlterField(
            model_name='user_groups',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='episode_genre',
            name='id_episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.episode'),
        ),
        migrations.AddField(
            model_name='episode_genre',
            name='id_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genre'),
        ),
        migrations.AddField(
            model_name='podcast_genre',
            name='id_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genre'),
        ),
        migrations.AddField(
            model_name='podcast_genre',
            name='id_podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.podcast'),
        ),
    ]
